CREATE PROCEDURE SP_INSERIRPRODUTO
	@NOME		NVARCHAR(150), --parametro de entrada
	@PRECO		DECIMAL(18,2), --parametro de entrada
	@QUANTIDADE	INTEGER --parametro de entrada
AS
BEGIN

	INSERT INTO PRODUTO
	(IDPRODUTO, NOME, PRECO, QUANTIDADE, DATACADASTRO)
	VALUES
	(NEWID(), @NOME, @PRECO, @QUANTIDADE, GETDATE())

END
GO