CREATE TABLE USUARIO(
	IDUSUARIO		UNIQUEIDENTIFIER		NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	EMAIL			NVARCHAR(100)		NOT NULL UNIQUE,
	SENHA			NVARCHAR(50)		NOT NULL,
	DATACADASTRO	DATETIME			NOT NULL,
	PRIMARY KEY(IDUSUARIO))
GO

CREATE PROCEDURE SP_INSERIRUSUARIO
	@NOME		NVARCHAR(150),
	@EMAIL	NVARCHAR(100),
	@SENHA	NVARCHAR(50)
AS
BEGIN

	INSERT INTO USUARIO(
		IDUSUARIO,
		NOME,
		EMAIL,
		SENHA,
		DATACADASTRO)
	VALUES(
		NEWID(), --gerando o id do usuario (guid)
		@NOME,
		@EMAIL,
		CONVERT(VARCHAR(32), HASHBYTES('MD5', @SENHA), 2), --criptografia da senha
		GETDATE()) --gerando a data atual do banco
END

CREATE PROCEDURE SP_CONSULTARUSUARIO
	@EMAIL		NVARCHAR(150),
	@SENHA		NVARCHAR(50)
AS
BEGIN

	SELECT * FROM USUARIO
	WHERE
		EMAIL = @EMAIL
		AND
		SENHA = CONVERT(
			VARCHAR(32), HASHBYTES(
				'MD5', @SENHA
			), 2)
END
